kibot:
  version: 1

preflight:
  erc: true
  drc: true

outputs:
  - name: schematic_pdf
    type: pdf_sch_print
    dir: documentation

  - name: pcb_pdf
    type: pcb_print
    dir: documentation
    options:
      format: PDF
      output: '%f-pcb.%x'
      force_edge_cuts: true
      pages:
        - sheet: Front PCB
          layers: [F.Cu, F.SilkS]
        - sheet: Back PCB
          layers: [B.Cu, B.SilkS]

  - name: fabrication_gerbers
    type: gerber
    dir: fabrication
    layers:
      - copper
      - F.Paste
      - B.Paste
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts
    options:
      use_protel_extensions: true
      create_gerber_job_file: true

  - name: fabrication_drills
    type: excellon
    dir: fabrication
    options:
      metric_units: true
      pth_and_npth_single_file: false

  - name: bom_csv
    type: bom
    dir: bom
    options:
      format: CSV

  - name: bom_xlsx
    type: bom
    dir: bom
    options:
      format: XLSX

  - name: interactive_bom
    type: ibom
    dir: bom

  - name: pick_and_place
    type: position
    dir: assembly
    options:
      format: CSV
      units: millimeters
      only_smd: true
      separate_files_for_front_and_back: true
      use_aux_axis_as_origin: false

  - name: board_step
    type: export_3d
    dir: 3d
    options:
      format: step
