kibot:
  version: 1

global:
  date_format: '%Y-%m-%d'
  date_time_format: '%Y-%m-%d'

preflight:
  erc: true
  drc: true
  draw_fancy_stackup:
    layer: FabricationNotes
    group_name: stackup

outputs:

# ----------------------------------------------------------------------------
  - name: blender_render
    type: blender_export
    run_by_default: false
    dir: 3d
    options:
      light:
#        - name: sunlight
#          type: SUN
#          pos_x: '-size*3.33'
#          pos_y: 'size*3.33'
#          pos_z: 'size*5'
#          energy: 2
        - name: softbox
          type: AREA
          pos_x: '-size*3.33'
          pos_y: 'size*3.33'
          pos_z: 'size*5'
          energy: @AUTO_LIGHT_ENERGY@
      outputs:
        - type: render
          output: '%f-%i.%x'
      render_options:
        auto_crop: true
        transparent_background: true
        samples: @RENDER_SAMPLES_@RENDER_MODE@@
        resolution_x: @RENDER_WIDTH_@RENDER_MODE@@
        resolution_y: @RENDER_HEIGHT_@RENDER_MODE@@

  - name: blender_top
    type: blender_export
    extends: blender_render
    dir: 3d
    run_by_default: @RENDER_RUN_@RENDER_MODE@@
    priority: 90
    options:
      point_of_view:
        - view: top
          file_id: top

  - name: blender_bottom
    type: blender_export
    extends: blender_render
    dir: 3d
    run_by_default: @RENDER_RUN_@RENDER_MODE@@
    priority: 90
    options:
      point_of_view:
        - view: bottom
          file_id: bottom

  - name: blender_angled_top
    type: blender_export
    extends: blender_render
    dir: 3d
    run_by_default: @RENDER_RUN_@RENDER_MODE@@
    priority: 90
    options:
      point_of_view:
        - view: top
          rotate_x: 15
          rotate_y: 25
          rotate_z: 0
          file_id: angled_top

  - name: blender_angled_bottom
    type: blender_export
    extends: blender_render
    dir: 3d
    run_by_default: @RENDER_RUN_@RENDER_MODE@@
    priority: 90
    options:
      point_of_view:
        - view: bottom
          rotate_x: -15
          rotate_y: 25
          rotate_z: 0
          file_id: angled_bottom

  - name: blender_bare_top
    comment: Bare board top view
    type: blender_export
    extends: blender_render
    dir: 3d
    run_by_default: @RENDER_RUN_@RENDER_MODE@@
    priority: 90
    options:
      pcb_import:
        components: false
        solder_joints: NONE
      point_of_view:
        - view: top
          file_id: bare_top

  - name: blender_bare_bottom
    comment: Bare board bottom view
    type: blender_export
    extends: blender_render
    dir: 3d
    run_by_default: @RENDER_RUN_@RENDER_MODE@@
    priority: 90
    options:
      pcb_import:
        components: false
        solder_joints: NONE
      point_of_view:
        - view: bottom
          file_id: bare_bottom



# ----------------------------------------------------------------------------

  - name: schematic_pdf
    type: pdf_sch_print
    dir: documentation


# ----------------------------------------------------------------------------

  - name: drillmap
    comment: Drill details for fabrication drawings
    type: excellon
    dir: fabrication/tables
    options:
      generate_drill_files: false
      table:
        output: '%f-%i.%x'
        units: millimeters
        unify_pth_and_npth: 'no'
        group_slots_and_round_holes: true
        columns:
          - Count
          - Hole Size
          - Plated
          - Hole Shape
          - Drill Layer Pair


# ----------------------------------------------------------------------------

  - name: pcb_fabrication_pdf
    comment: Fabrication drawing
    type: pcb_print
    dir: documentation
    options:
      color_theme: _builtin_classic
      output: '%f-pcb-fabrication.%x'
      format: PDF
      title: fabrication drawing
      scaling: 1.0
      plot_sheet_reference: true
      frame_plot_mechanism: internal
      colored_pads: false
      colored_vias: false
      realistic_solder_mask: false
      dpi: 1200
      sheet_reference_layout: ''
      drill:
        unify_pth_and_npth: 'no'
        group_slots_and_round_holes: true
      include_table:
        outputs:
          - name: drillmap
            text_alignment: left
            border_width: 0.4
            header_rule_width: 0.2
            horizontal_rule_width: 0
            vertical_rule_width: 0.2
            top_rule_width: 0.2
            bottom_rule_width: 0.2
            row_spacing: 3
            column_spacing: 2

      pages:
        - sheet: 'Bare board overview'
          layer_var: ''
          sheet_reference_color: '#000000'
          layers: @FAB_OVERVIEW_LAYERS_@RENDER_MODE@@

        - sheet: 'Fabrication requirements'
          layer_var: 'Fabrication requirements'
          sheet_reference_color: '#000000'
          layers:
            - layer: FabricationNotes
              color: '#000000'

        - sheet: 'Top fabrication (scale 1:1)'
          layer_var: 'Top fabrication (scale 1:1)'
          sheet_reference_color: '#000000'
          colored_holes: true
          holes_color: '#FFFFFF'
          layers:
            - layer: Edge.Cuts
              color: '#000000'
            - layer: F.Cu
              color: '#F2F2F2'
            - layer: F.Mask
              color: '#E2E2E2'
            - layer: F.Paste
              color: '#E2E2E2'
            - layer: F.Silkscreen
              color: '#DBDBDB'
            - layer: TopDimensions
              color: '#000000'

        - sheet: 'Bottom fabrication (scale 1:1)'
          layer_var: 'Bottom fabrication (scale 1:1)'
          mirror: true
          mirror_pcb_text: true
          sheet_reference_color: '#000000'
          colored_holes: true
          holes_color: '#FFFFFF'
          layers:
            - layer: Edge.Cuts
              color: '#000000'
            - layer: B.Cu
              color: '#F2F2F2'
            - layer: B.Mask
              color: '#E2E2E2'
            - layer: B.Paste
              color: '#E2E2E2'
            - layer: B.Silkscreen
              color: '#DBDBDB'
            - layer: BottomDimensions
              color: '#000000'

        - sheet: 'Drill drawing — %lp (scale 1:1)'
          layer_var: 'Drill drawing — %lp (scale 1:1)'
          repeat_for_layer: FabricationDrillMap
          repeat_layers: drill_pairs
          sheet_reference_color: '#000000'
          layers:
            - layer: FabricationDrillMap
              color: '#000000'
            - layer: Edge.Cuts
              color: '#000000'

        - sheet: '%ln (scale 1:1)'
          layer_var: '%ln (scale 1:1)'
          repeat_for_layer: F.Cu
          repeat_layers: copper
          repeat_inherit: false
          sheet_reference_color: '#000000'
          colored_holes: true
          holes_color: '#FFFFFF'
          layers:
            - layer: F.Cu
#              color: '#000000'
            - layer: Edge.Cuts
              color: '#000000'

        - sheet: 'F.Mask (scale 1:1)'
          layer_var: 'F.Mask (scale 1:1)'
          sheet_reference_color: '#000000'
          colored_holes: true
          holes_color: '#FFFFFF'
          layers:
            - layer: F.Mask
 #             color: '#000000'
            - layer: Edge.Cuts
              color: '#000000'

        - sheet: 'B.Mask (scale 1:1)'
          layer_var: 'B.Mask (scale 1:1)'
          sheet_reference_color: '#000000'
          colored_holes: true
          holes_color: '#FFFFFF'
          layers:
            - layer: B.Mask
  #            color: '#000000'
            - layer: Edge.Cuts
              color: '#000000'

        - sheet: 'F.Silkscreen (scale 1:1)'
          layer_var: 'F.Silkscreen (scale 1:1)'
          sheet_reference_color: '#000000'
          colored_holes: true
          holes_color: '#FFFFFF'
          layers:
            - layer: F.Silkscreen
              color: '#000000'
            - layer: Edge.Cuts
              color: '#000000'

        - sheet: 'B.Silkscreen (scale 1:1)'
          layer_var: 'B.Silkscreen (scale 1:1)'
          sheet_reference_color: '#000000'
          colored_holes: true
          holes_color: '#FFFFFF'
          layers:
            - layer: B.Silkscreen
              color: '#000000'
            - layer: Edge.Cuts
              color: '#000000'


# ----------------------------------------------------------------------------


  - name: parts_count_top
    comment: Fitted component counts on top side
    type: report
    dir: assembly/tables
    options:
      template: Template/assembly_count_top.txt
      output: '%f-assembly-count-top.csv'
      do_convert: false

  - name: parts_count_bottom
    comment: Fitted component counts on bottom side
    type: report
    dir: assembly/tables
    options:
      template: Template/assembly_count_bottom.txt
      output: '%f-assembly-count-bottom.csv'
      do_convert: false

# ----------------------------------------------------------------------------


  - name: pcb_assembly_pdf
    comment: Assembly drawing
    type: pcb_print
    dir: documentation
    options:
      output: '%f-pcb-assembly.%x'
      format: PDF
      title: Assembly drawing
      sheet_reference_layout: ''
      plot_sheet_reference: true
      frame_plot_mechanism: internal
      force_edge_cuts: false
      colored_pads: false
      colored_vias: false
      realistic_solder_mask: false
      dpi: 1200
      scaling: 1.0
      include_table:
        outputs:
          - name: parts_count_top
            text_alignment: left
            invert_columns_order: false
            border_width: 0.4
            header_rule_width: 0.2
            horizontal_rule_width: 0
            vertical_rule_width: 0.2
            top_rule_width: 0 #0.2
            bottom_rule_width: 0 #0.2
            row_spacing: 3
            column_spacing: 2
            #force_font_width: 1.0

          - name: parts_count_bottom
            text_alignment: right
            invert_columns_order: true
            border_width: 0.4
            header_rule_width: 0.2
            horizontal_rule_width: 0
            vertical_rule_width: 0.2
            top_rule_width: 0.2
            bottom_rule_width: 0.2
            row_spacing: 3
            column_spacing: 2
            #force_font_width: 1.0

      pages:
        - sheet: 'Assembly overview'
          layer_var: ''
          sheet_reference_color: '#000000'
          layers: @OVERVIEW_LAYERS_@RENDER_MODE@@

        - sheet: 'Top assembly (Scale 1:1)'
          layer_var: 'Top assembly (Scale 1:1)'
          sheet_reference_color: '#000000'
          colored_holes: true
          holes_color: '#FFFFFF'
          layers:
            - layer: Edge.Cuts
              color: '#000000'
            - layer: F.Cu
              color: '#EEDAB5'
            - layer: F.Mask
              color: '#B9B9B9'
            - layer: F.Paste
              color: '#E1A98E'
            - layer: F.Fab
              color: '#744679'
            @IMAGE_COMMENT_@RENDER_MODE@@- {layer: AssemblyTop, color: '#000000'}

        - sheet: 'Bottom assembly (Scale 1:1)'
          layer_var: 'Bottom assembly (Scale 1:1)'
          mirror: true
          mirror_pcb_text: true
          sheet_reference_color: '#000000'
          colored_holes: true
          holes_color: '#FFFFFF'
          layers:
            - layer: Edge.Cuts
              color: '#000000'
            - layer: B.Cu
              color: '#D5DBF4'
            - layer: B.Mask
              color: '#B9B9B9'
            - layer: B.Paste
              color: '#BCB9DD'
            - layer: B.Fab
              color: '#400080'
            @IMAGE_COMMENT_@RENDER_MODE@@- {layer: AssemblyBottom, color: '#000000'}


# ----------------------------------------------------------------------------

  - name: fabrication_gerbers
    type: gerber
    dir: fabrication
    layers:
      - copper
      - F.Paste
      - B.Paste
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts
    options:
      use_protel_extensions: true
      create_gerber_job_file: true

# ----------------------------------------------------------------------------

  - name: fabrication_drills
    type: excellon
    dir: fabrication
    options:
      metric_units: true
      pth_and_npth_single_file: false

# ----------------------------------------------------------------------------

  - name: bom_csv
    type: bom
    dir: bom
    options:
      format: CSV

# ----------------------------------------------------------------------------

  - name: bom_xlsx
    type: bom
    dir: bom
    options:
      format: XLSX

# ----------------------------------------------------------------------------

  - name: interactive_bom
    type: ibom
    dir: bom

# ----------------------------------------------------------------------------

  - name: pick_and_place
    type: position
    dir: assembly
    options:
      format: CSV
      units: millimeters
      only_smd: true
      separate_files_for_front_and_back: true
      use_aux_axis_as_origin: false

# ----------------------------------------------------------------------------

  - name: board_step
    type: export_3d
    dir: 3d
    options:
      format: step

...
definitions:
  RENDER_MODE: 'high'  # disabled, low, high

  RENDER_RUN_disabled: 'false'
  RENDER_RUN_low: 'true'
  RENDER_RUN_high: 'true'

  IMAGE_COMMENT_disabled: '#'
  IMAGE_COMMENT_low: ''
  IMAGE_COMMENT_high: ''

  OVERVIEW_LAYERS_disabled: '[]'
  OVERVIEW_LAYERS_low: '[{layer: AssemblyOverview, color: "#000000"}]'
  OVERVIEW_LAYERS_high: '[{layer: AssemblyOverview, color: "#000000"}]'

  RENDER_SAMPLES_disabled: '1'
  RENDER_SAMPLES_low: '2'
  RENDER_SAMPLES_high: '16'

  RENDER_WIDTH_disabled: '270'
  RENDER_WIDTH_low: '480'
  RENDER_WIDTH_high: '1280'

  RENDER_HEIGHT_disabled: '270'
  RENDER_HEIGHT_low: '480'
  RENDER_HEIGHT_high: '1280'

  FAB_OVERVIEW_LAYERS_disabled: '[]'
  FAB_OVERVIEW_LAYERS_low: '[{layer: FabricationRender, color: "#000000"}]'
  FAB_OVERVIEW_LAYERS_high: '[{layer: FabricationRender, color: "#000000"}]'
